version: '3'

services:
  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.3
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"

  db:
    container_name: postgres_container
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # adding another container to handle Python scripts that do specific tasks
  # such as data loading, language translation and sentiment analysis
  # helps manage dependencies & build reproducible environments
  python-app:
    container_name: python_container
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  postgres_data:
